## Gozlem Ve Degisken Secimi

In [62]:
import numpy as np
import pandas as pd
m=np.random.randint(1,30,size=(10,3))
df=pd.DataFrame(m,columns=["var1","var2","var3"])
df

   var1  var2  var3
0     3    20    27
1    11     3    13
2    25    18    21
3    20    20    18
4    13    17    22
5    24     2    21
6    28    27     3
7     4    14    15
8     3    11    27
9     2    27    18

In [63]:
#loc---> secim yapmak icin

In [64]:
df.loc[0:3] #3ude alıyor

   var1  var2  var3
0     3    20    27
1    11     3    13
2    25    18    21
3    20    20    18

In [65]:
#iloc --> indekslemeyle secim yapar

In [66]:
df.iloc[0:3]

   var1  var2  var3
0     3    20    27
1    11     3    13
2    25    18    21

In [67]:
df.iloc[0,0]

3

In [68]:
df.loc[0:3,"var3"]

0    27
1    13
2    21
3    18
Name: var3, dtype: int32

In [69]:
#mutlak bir degisken vericeksek loc kullanılır

## Kosullu Eleman

In [70]:
df

   var1  var2  var3
0     3    20    27
1    11     3    13
2    25    18    21
3    20    20    18
4    13    17    22
5    24     2    21
6    28    27     3
7     4    14    15
8     3    11    27
9     2    27    18

In [71]:
df.var1

0     3
1    11
2    25
3    20
4    13
5    24
6    28
7     4
8     3
9     2
Name: var1, dtype: int32

In [72]:
df[df.var1>15] #kosul calıstırma

   var1  var2  var3
2    25    18    21
3    20    20    18
5    24     2    21
6    28    27     3

In [73]:
df[(df.var1>15) & (df.var3<5)] #ortak satırı aldı

   var1  var2  var3
6    28    27     3

## join

In [74]:
import numpy as np
import pandas as pd
m=np.random.randint(1,30,size=(5,3))
df1=pd.DataFrame(m,columns=["var1","var2","var3"])
df1

   var1  var2  var3
0    11     5    28
1    17    13    12
2     8    23    15
3    20    10    29
4    12     2    24

In [75]:
df2=df1+99

In [76]:
df2

   var1  var2  var3
0   110   104   127
1   116   112   111
2   107   122   114
3   119   109   128
4   111   101   123

In [77]:
pd.concat([df1,df2],ignore_index=True) #birlesti

   var1  var2  var3
0    11     5    28
1    17    13    12
2     8    23    15
3    20    10    29
4    12     2    24
5   110   104   127
6   116   112   111
7   107   122   114
8   119   109   128
9   111   101   123

In [78]:
df.columns

Index(['var1', 'var2', 'var3'], dtype='object')

In [79]:
df1.columns=["var1","var2","deg3"]

In [80]:
df1

   var1  var2  deg3
0    11     5    28
1    17    13    12
2     8    23    15
3    20    10    29
4    12     2    24

In [81]:
pd.concat([df1,df2], join="inner")

   var1  var2
0    11     5
1    17    13
2     8    23
3    20    10
4    12     2
0   110   104
1   116   112
2   107   122
3   119   109
4   111   101

In [82]:
#ileri  birlestirme

In [95]:
import numpy as np
import pandas as pd

df1=pd.DataFrame({'ogrenciler':['ali','veli','fatma'],'bolum':['muhendislik','tıp','isletme']})

In [96]:
df1

  ogrenciler        bolum
0        ali  muhendislik
1       veli          tıp
2      fatma      isletme

In [97]:
df2=pd.DataFrame({'ogrenciler':['ali','veli','fatma'],'ortalama':[3,2.4,3.5]})

In [98]:
df2

  ogrenciler  ortalama
0        ali       3.0
1       veli       2.4
2      fatma       3.5

In [100]:
pd.merge(df1,df2) #ogrencilere gore birlestirdi

  ogrenciler        bolum  ortalama
0        ali  muhendislik       3.0
1       veli          tıp       2.4
2      fatma      isletme       3.5

In [101]:
#coktan teke

In [102]:
df3=pd.merge(df1,df2)

In [114]:
df4=pd.DataFrame({'ogrenciler':['ali','veli','fatma'],'konu':['goruntu isleme','pediatri','isletme']})

In [115]:
df4

  ogrenciler            konu
0        ali  goruntu isleme
1       veli        pediatri
2      fatma         isletme

In [116]:
pd.merge(df3,df4)

  ogrenciler        bolum  ortalama            konu
0        ali  muhendislik       3.0  goruntu isleme
1       veli          tıp       2.4        pediatri
2      fatma      isletme       3.5         isletme