## Toplulastırma &Gruplama

In [5]:
import seaborn as sns

In [12]:
df=sns.load_dataset("planets")  #seaborn kutuphanesinden ozel bir veri seti aldık

In [10]:
df.head()

            method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [11]:
df.shape

(1035, 6)

In [13]:
df.mean()

number               1.785507
orbital_period    2002.917596
mass                 2.638161
distance           264.069282
year              2009.070531
dtype: float64

In [14]:
df["mass"].mean()

2.6381605847953233

In [15]:
df["mass"].min()

0.0036

In [16]:
df["mass"].max()

25.0

In [17]:
df["mass"].std()

3.8186166509616046

In [18]:
df.describe()

            number  orbital_period        mass     distance         year
count  1035.000000      992.000000  513.000000   808.000000  1035.000000
mean      1.785507     2002.917596    2.638161   264.069282  2009.070531
std       1.240976    26014.728304    3.818617   733.116493     3.972567
min       1.000000        0.090706    0.003600     1.350000  1989.000000
25%       1.000000        5.442540    0.229000    32.560000  2007.000000
50%       1.000000       39.979500    1.260000    55.250000  2010.000000
75%       2.000000      526.005000    3.040000   178.500000  2012.000000
max       7.000000   730000.000000   25.000000  8500.000000  2014.000000

In [19]:
#daha duzgun gorulsun

In [21]:
df.describe().T #transpoze

,count,mean,std,min,25%,50%,75%,max
number,1035.0,1.785507,1.240976,1.000000,1.00000,1.0000,2.000,7.0
orbital_period,992.0,2002.917596,26014.728304,0.090706,5.44254,39.9795,526.005,730000.0
mass,513.0,2.638161,3.818617,0.003600,0.22900,1.2600,3.040,25.0
distance,808.0,264.069282,733.116493,1.350000,32.56000,55.2500,178.500,8500.0
year,1035.0,2009.070531,3.972567,1989.000000,2007.00000,2010.0000,2012.000,2014.0

In [23]:
df.dropna().describe().T #eksikleri sildik

,count,mean,std,min,25%,50%,75%,max
number,498.0,1.734940,1.175720,1.0000,1.00000,1.000,2.0000,6.0
orbital_period,498.0,835.778671,1469.128259,1.3283,38.27225,357.000,999.6000,17337.5
mass,498.0,2.509320,3.636274,0.0036,0.21250,1.245,2.8675,25.0
distance,498.0,52.068213,46.596041,1.3500,24.49750,39.940,59.3325,354.0
year,498.0,2007.377510,4.167284,1989.0000,2005.00000,2009.000,2011.0000,2014.0

In [43]:
df=sns.load_dataset("planets")  
df.head()

            method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [45]:
df.groupby("method") #buna gore grupla

In [47]:
df.groupby("method")["orbital_period"].mean()  #gruplara karsılık gelen orb

method
Astrometry                          631.180000
Eclipse Timing Variations          4751.644444
Imaging                          118247.737500
Microlensing                       3153.571429
Orbital Brightness Modulation         0.709307
Pulsar Timing                      7343.021201
Pulsation Timing Variations        1170.000000
Radial Velocity                     823.354680
Transit                              21.102073
Transit Timing Variations            79.783500
Name: orbital_period, dtype: float64

In [48]:
#ve ortalama aldık

In [50]:
df.groupby("method")["orbital_period"].describe() #standart s /ort hepsini verdi

,count,mean,std,min,25%,50%,75%,max
method,,,,,,,,
Astrometry,2.0,631.180000,544.217663,246.360000,438.770000,631.180000,823.590000,1016.000000
Eclipse Timing Variations,9.0,4751.644444,2499.130945,1916.250000,2900.000000,4343.500000,5767.000000,10220.000000
Imaging,12.0,118247.737500,213978.177277,4639.150000,8343.900000,27500.000000,94250.000000,730000.000000
Microlensing,7.0,3153.571429,1113.166333,1825.000000,2375.000000,3300.000000,3550.000000,5100.000000
Orbital Brightness Modulation,3.0,0.709307,0.725493,0.240104,0.291496,0.342887,0.943908,1.544929
Pulsar Timing,5.0,7343.021201,16313.265573,0.090706,25.262000,66.541900,98.211400,36525.000000
Pulsation Timing Variations,1.0,1170.000000,NaN,1170.000000,1170.000000,1170.000000,1170.000000,1170.000000
Radial Velocity,553.0,823.354680,1454.926210,0.736540,38.021000,360.200000,982.000000,17337.500000
Transit,397.0,21.102073,46.185893,0.355000,3.160630,5.714932,16.145700,331.600590
Transit Timing Variations,3.0,79.783500,71.599884,22.339500,39.675250,57.011000,108.505500,160.000000

## agregate

In [88]:
import pandas as pd
import numpy as np

In [89]:
df1=pd.DataFrame({'grup':['A','B','C'],'degisken1':[10,2,3],
                 'degisken2':[234,56,36]},
               columns=['grup','degisken1','degisken2'])

In [90]:
df1

  grup  degisken1  degisken2
0    A         10        234
1    B          2         56
2    C          3         36

In [91]:
#aggregate

In [92]:
df1.groupby("grup").mean()

      degisken1  degisken2
grup
A            10        234
B             2         56
C             3         36

In [94]:
df1.groupby("grup").aggregate(["min",np.median,max])  #pandasta min var "" aldık

     degisken1            degisken2
           min median max       min median  max
grup
A           10     10  10       234    234  234
B            2      2   2        56     56   56
C            3      3   3        36     36   36

## Filter

In [123]:
df=pd.DataFrame({'grup':['A','B','C'],'degisken1':[10,23,31],
                 'degisken2':[24,56,3]},
               columns=['grup','degisken1','degisken2'])
df

  grup  degisken1  degisken2
0    A         10         24
1    B         23         56
2    C         31          3

In [124]:
def filtrele(x):
    return x["degisken1"].std()>9

#degisken1 e gore st spmsı 9dan buyuk olanları al dedik

In [125]:
df1.groupby("grup").std()

      degisken1  degisken2
grup
A           NaN        NaN
B           NaN        NaN
C           NaN        NaN

In [126]:

df1.groupby("grup").filter(filtrele)

Empty DataFrame
Columns: [grup, degisken1, degisken2]
Index: []

# Transforms

In [153]:
df1=pd.DataFrame({'grup':['A','B','C'],'degisken1':[10,2,3],
                 'degisken2':[234,56,36]},
               columns=['grup','degisken1','degisken2'])
df1

  grup  degisken1  degisken2
0    A         10        234
1    B          2         56
2    C          3         36

In [154]:
df["degisken1"]*9

0     90
1    207
2    279
Name: degisken1, dtype: int64

In [155]:
df_a=df.iloc[:,1:3]  #loc ve iloc # index seklinde olsun diye

In [156]:
df_a.transform(lambda x:x-x.mean()) #kategorik degsk olmamalı

   degisken1  degisken2
0 -11.333333  -3.666667
1   1.666667  28.333333
2   9.666667 -24.666667

# apply

In [157]:
df1=pd.DataFrame({'degisken1':[10,2,3],
                 'degisken2':[234,56,36]},
               columns=['degisken1','degisken2'])
df1

   degisken1  degisken2
0         10        234
1          2         56
2          3         36

In [159]:
df1.apply(np.sum)  #her birinin toplam

degisken1     15
degisken2    326
dtype: int64

In [161]:
df1.apply(np.mean)

degisken1      5.000000
degisken2    108.666667
dtype: float64

In [ ]:
#gruplarda sum old. string toplaması yapar.

# Pivot

In [164]:
import pandas as pd
import seaborn as sns

In [165]:
titanic=sns.load_dataset('titanic')

In [166]:
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [168]:
titanic.groupby("sex")["survived"].mean() #cinsiyete gore gruplayıp hayatta kalanlar

sex
female    0.742038
male      0.188908
Name: survived, dtype: float64

In [172]:
titanic.groupby(["class","sex"])[["survived"]].aggregate("mean").unstack()

        survived
sex       female      male
class
First   0.968085  0.368852
Second  0.921053  0.157407
Third   0.500000  0.135447

In [173]:
#unstack kaldırılınca yapı zor okunuyor

In [174]:
#pivot

In [175]:
titanic.pivot_table("survived",index="sex",columns="class")

class      First    Second     Third
sex
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [177]:
titanic.age.head()

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
Name: age, dtype: float64

In [179]:
age=pd.cut(titanic["age"],[0,18,90]) #yas aralıklarını bol
age.head(10)

0    (18.0, 90.0]
1    (18.0, 90.0]
2    (18.0, 90.0]
3    (18.0, 90.0]
4    (18.0, 90.0]
5             NaN
6    (18.0, 90.0]
7     (0.0, 18.0]
8    (18.0, 90.0]
9     (0.0, 18.0]
Name: age, dtype: category
Categories (2, interval[int64]): [(0, 18] < (18, 90]]

In [183]:
titanic.pivot_table("survived",["sex",age],"class")  #kategorik aldık ageyi

class               First    Second     Third
sex    age
female (0, 18]   0.909091  1.000000  0.511628
       (18, 90]  0.972973  0.900000  0.423729
male   (0, 18]   0.800000  0.600000  0.215686
       (18, 90]  0.375000  0.071429  0.133663