In [2]:
#pandas serileri

In [3]:
import pandas as pd

In [6]:
pd.Series([1,2,3,45,"ali"]) #string vs de alır degerleri indexiyle tutar

0      1
1      2
2      3
3     45
4    ali
dtype: object

In [7]:
a =pd.Series([1,2,3,45,"ali"])

In [8]:
type(a)

pandas.core.series.Series

In [11]:
a.axes #baslangıc bitis

[RangeIndex(start=0, stop=5, step=1)]

In [18]:
a.dtype #data tipleri

dtype('O')

In [19]:
a.size  #eleman sayısı

5

In [20]:
a.ndim  #boyut

1

In [21]:
a.values

array([1, 2, 3, 45, 'ali'], dtype=object)

In [23]:
a.head(3)  #3 ekadar getir linuxtaki dosya okuma gibi

0    1
1    2
2    3
dtype: object

In [24]:
a.tail(2)

3     45
4    ali
dtype: object

In [25]:
#index isimlendirme

In [34]:
pd.Series([8,767,34323,1212,11],index=[1,3,67,8,328])
                                           #istedigin index no'sunu ata

1          8
3        767
67     34323
8       1212
328       11
dtype: int64

In [36]:
a[1]

2

In [37]:
#sozlukten seri

In [38]:
soz=pd.Series({"reg":10,"log":11})

In [39]:
soz

reg    10
log    11
dtype: int64

In [40]:
soz=pd.Series({"reg":10,"log":11})

In [43]:
seri =pd.Series(soz)  #series içine

In [45]:
seri  #sozluk usutunden olustu

reg    10
log    11
dtype: int64

In [46]:
#2seriden

In [47]:
pd.concat([seri,seri])

reg    10
log    11
reg    10
log    11
dtype: int64

In [48]:
#eleman islemleri

In [49]:
import numpy as np

In [50]:
a=np.array([1,2,34,45,5])

In [52]:
seri=pd.Series(a)
seri

0     1
1     2
2    34
3    45
4     5
dtype: int32

In [55]:
seri[0]
seri[0:3]#slicing

0     1
1     2
2    34
dtype: int32

In [58]:
seri=pd.Series([1,32,4],index=["reg","log","cart"])

In [59]:
seri.index

Index(['reg', 'log', 'cart'], dtype='object')

In [60]:
seri.keys

<bound method Series.keys of reg      1
log     32
cart     4
dtype: int64>

In [61]:
list(seri.items())

[('reg', 1), ('log', 32), ('cart', 4)]

In [62]:
#eleman sorgu

In [64]:
"reg" in seri

True

In [65]:
#fancy ile secme

In [67]:
seri["reg"]

1

In [68]:
seri["reg"]=4545

In [69]:
seri

reg     4545
log       32
cart       4
dtype: int64

In [70]:
 #indexlere eriştik ve degistirdik

## Pandas DataFrame

In [71]:
import pandas as pd

In [72]:
l=[1,2,32,54,78]

In [73]:
l

[1, 2, 32, 54, 78]

In [77]:
pd.DataFrame(l,columns=["isim"])

   isim
0     1
1     2
2    32
3    54
4    78

In [82]:
import numpy as np
m=np.arange(1,10).reshape((3,3))
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [86]:
pd.DataFrame(m,columns=["var1","var2","var3"])  #ilk data Frame

   var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [87]:
#df isimlendirme

In [88]:
df=pd.DataFrame(m,columns=["var1","var2","var3"])

In [89]:
df.head()

   var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [90]:
df.columns

Index(['var1', 'var2', 'var3'], dtype='object')

In [91]:
df

   var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [93]:
type(df)  #tip bilgisi

pandas.core.frame.DataFrame

In [96]:
df.shape

(3, 3)

In [97]:
df.ndim

2

In [99]:
df.size  #eleman sayisi

9

In [101]:
df.values  #arraye cevirdi

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [102]:
df.tail(1)

   var1  var2  var3
2     7     8     9

In [108]:
a=np.array([1,2,3,4])  #np arrayinden data Frame

In [109]:
pd.DataFrame(a,columns=["var1"])

   var1
0     1
1     2
2     3
3     4

In [110]:
#eleman islemleri

In [113]:
import numpy as np
s1=np.random.randint(10,size=5)
s2=np.random.randint(10,size=5)
s3=np.random.randint(10,size=5)

In [117]:
sozluk={"var1":s1,"var2":s2,"var3":s3}  #sozlk--> np array

In [118]:
sozluk

{'var1': array([6, 4, 3, 3, 7]),
 'var2': array([3, 9, 0, 3, 4]),
 'var3': array([1, 4, 0, 2, 3])}

In [119]:
df=pd.DataFrame(sozluk)

In [122]:
df  #indexleri kendi

   var1  var2  var3
0     6     3     1
1     4     9     4
2     3     0     0
3     3     3     2
4     7     4     3

In [123]:
df[0:1]

   var1  var2  var3
0     6     3     1

In [125]:
#silme

In [131]:
df.drop(1,axis=0)

   var1  var2  var3
0     6     3     1
2     3     0     0
3     3     3     2
4     7     4     3

In [132]:
df

   var1  var2  var3
0     6     3     1
1     4     9     4
2     3     0     0
3     3     3     2
4     7     4     3

In [135]:
df.drop(2,axis=0,inplace=True)

In [137]:
df # 2.satır uctu

   var1  var2  var3
0     6     3     1
1     4     9     4
3     3     3     2
4     7     4     3

In [139]:
#degiskenler icin

In [140]:
df

   var1  var2  var3
0     6     3     1
1     4     9     4
3     3     3     2
4     7     4     3

In [141]:
"var1" in df

True

In [160]:
v=["var1","var4","var3"]

In [161]:
for i in v:  #var mı?
    print(i in df)

True
False
True

In [162]:
df

   var1  var2  var3
0     6     3     1
1     4     9     4
3     3     3     2
4     7     4     3

In [163]:
df["var1"]

0    6
1    4
3    3
4    7
Name: var1, dtype: int32

In [169]:
df["var4"]=df["var1"] /df["var3"] #yeni degiskeN

In [170]:
df

   var1  var2  var3      var4
0     6     3     1  6.000000
1     4     9     4  1.000000
3     3     3     2  1.500000
4     7     4     3  2.333333

In [171]:
df.drop("var4",axis=1,inplace=True)

In [172]:
df

   var1  var2  var3
0     6     3     1
1     4     9     4
3     3     3     2
4     7     4     3

In [173]:
#var 4 gitti